name: smart_home
description: "Smart home"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  zoom_tap_animation: ^1.1.0
  http: ^1.2.1
  flutter_bloc: ^8.1.6
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.7.0
  bloc_concurrency: ^0.2.5
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/Urbanist/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.otf
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.otf
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.otf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.otf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Light.otf
        - asset: assets/fonts/Urbanist/Urbanist-LightItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.otf
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Regular.otf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.otf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.otf
        - asset: assets/fonts/Urbanist/Urbanist-Thin.otf
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.otf